# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFpPjfbD5T_zK18rzR5n6g7L4RKpqCgx
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import random

def evaluate_model(model, test_loader, device):
    '''
    Evaluate the model on the test set and print out the accuracy achieved as
    well as the classification report.

    Arguments:
      model: the model to evaluate
      test_loader: the dataloader for the test set
      device: the device to use for evaluation

    Returns:
      accuracy: the accuracy of the model on the test set
      all_preds: the predictions of the model on the test set
      all_targets: the targets of the test set
      all_probs: the probabilities of the predictions
    '''
    print("\n Evaluating best model on test set")

    model.eval()

    all_preds, all_targets, all_probs = [], [], []
    with torch.no_grad():
        for data, targets in tqdm(test_loader, desc="Testing", leave=True):
            data, targets = data.to(device), targets.to(device)
            outputs = model(data)
            probs = F.softmax(outputs, dim=1)
            preds = probs.argmax(1)

            all_preds.extend(preds.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    # Compute metrics
    accuracy = (np.array(all_preds) == np.array(all_targets)).mean() * 100
    print(f"\n✅ Test Accuracy: {accuracy:.4f}%")
    print("\n Classification Report:")
    print(classification_report(all_targets, all_preds, target_names=["AD", "NC"], digits=4))

    return accuracy, all_preds, all_targets, all_probs

def plot_confusion_matrix(all_targets, all_preds):
    """
    Plot a confusion matrix for the given predictions and targets, as well as a
    normalised confusion matrix.

    Arguments:
      all_targets: the targets of the test set from 'evaluate_model()'
      all_preds: the predictions of the model from 'evaluate_model()'
    """
    cm = confusion_matrix(all_targets, all_preds)
    cm_norm = confusion_matrix(all_targets, all_preds, normalize="true")

    fig, ax = plt.subplots(1, 2, figsize=(12, 5))
    ConfusionMatrixDisplay(cm, display_labels=["AD", "NC"]).plot(ax=ax[0], cmap="Reds", colorbar=False)
    ax[0].set_title("Confusion Matrix (Raw)")

    ConfusionMatrixDisplay(cm_norm, display_labels=["AD", "NC"]).plot(ax=ax[1], cmap="Greens", colorbar=True)
    ax[1].set_title("Normalized Confusion Matrix")

    plt.tight_layout()
    plt.show()

def display_sample_predictions(dataset, num_samples=10):
    """
    Display a sample of predictions from the test set. Include their true label,
    predicted label, and the model's confidence about the prediction. These are
    colour coded for easy reference.

    Arguments:
      dataset: the test dataset
      num_samples: the number of sample predictions to display
    """

    print("\n Dipslay sample predictions from test set")

    class_names = ["AD", "NC"]

    # Select random samples from test set
    indices = random.sample(range(len(test_ds)), num_samples)
    samples = [test_ds[i] for i in indices]

    fig, axes = plt.subplots(2, 5, figsize=(15, 7))
    fig.suptitle("Sample Test Predictions", fontsize=16)

    for i, (img, true_label) in enumerate(samples):
        ax = axes[i // 5, i % 5]
        model_input = img.unsqueeze(0).to(device)
        with torch.no_grad():
            output = model(model_input)
            prob = F.softmax(output, dim=1).cpu().numpy()[0]
            pred_label = np.argmax(prob)
            confidence = prob[pred_label]

        # Denormalize image
        img_disp = img * 0.271 + 0.263
        img_disp = img_disp.squeeze(0).cpu().numpy()

        ax.imshow(img_disp, cmap="gray")
        ax.axis("off")

        title_color = "green" if pred_label == true_label else "red"
        ax.set_title(
            f"Pred: {class_names[pred_label]}\nTrue: {class_names[true_label]}\nConf: {confidence*100:.1f}%",
            fontsize=10,
            color=title_color,
        )

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

if __name__ == "__main__":

  
  import os
  cwd = os.getcwd()
  

  from dataset import *
  from modules import *

  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  print("Using:", device)


  
  # Get datset directories
  train_dir = os.path.join(cwd, "AD_NC", "train")
  test_dir  = os.path.join(cwd, "AD_NC", "test")
  save_dir = cwd
  

  # Get the test dataloader
  _, _, test_ds = create_datasets(train_dir, test_dir)
  _, _, test_loader = create_dataloaders(_, _, test_ds)

  # Create the model and load in the parameters corresponding to the highest validation accruacy
  model = ConvNeXt(in_chans=1, num_classes=2).to(device)
  model.load_state_dict(torch.load(os.path.join(save_dir, "best_convnext_adni.pth"), map_location=device))

  # Calculate the results of the evaluation
  accuracy, all_preds, all_targets, all_probs = evaluate_model(model, test_loader, device)

  plot_confusion_matrix(all_targets, all_preds)

  display_sample_predictions(test_ds)