# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRajoif3W2lLtZA5OndORVG0tWUkAIj3
"""

from dataset import *
from modules import *
from predict import evaluate_model, plot_confusion_matrix, display_sample_predictions

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
)
from torch.optim.lr_scheduler import SequentialLR, LinearLR, CosineAnnealingLR
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


cwd = os.getcwd()
# Set the paths to the training and testing directories
train_dir = os.path.join(cwd, "AD_NC", "train")
test_dir = os.path.join(cwd, "AD_NC", "test")


# Create dataloaders for the training, validation, and evaluation sets
train_ds, val_ds, test_ds = create_datasets(train_dir, test_dir)
train_loader, val_loader, test_loader = create_dataloaders(train_ds, val_ds, test_ds)

def run_epoch(model, loader, criterion=None, optimizer=None, train=True):
    """
    Run a single epoch of training or validation. When called, the caller can
    specify whether they want to update the model's parameters (train=True) or
    not (train=False).

    Arguments:
      model: the model to train or evaluate
      loader: the dataloader for the dataset (training or validaiton)
      criterion: the loss function (only used as a statistic for validation)
      optimizer: the optimizer (only used in training)

    Returns:
      avg_loss: the average loss over the epoch
      accuracy: the accuracy over the epoch
      f1: the f1 score over the epoch
    """
    model.train(train)
    total_loss, correct, total = 0.0, 0, 0
    all_preds, all_targets = [], []

    loop = tqdm(loader, desc="Training" if train else "Validation", leave=True)
    for data, targets in loop:
        data, targets = data.to(device), targets.to(device)

        outputs = model(data)
        loss = criterion(outputs, targets)

        if train:

            optimizer.zero_grad()
            loss.backward() # Backpropogate the loss
            optimizer.step() # Step the optimizer

        total_loss += loss.item()
        _, preds = outputs.max(1)
        total += targets.size(0)
        correct += preds.eq(targets).sum().item()
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(targets.cpu().numpy())

        acc = 100 * correct / total
        loop.set_postfix(Loss=f"{loss.item():.4f}", Acc=f"{acc:.2f}%")

    avg_loss = total_loss / len(loader)
    accuracy = 100 * correct / total
    f1 = f1_score(all_targets, all_preds, average="macro")
    return avg_loss, accuracy, f1

'''
model = ConvNeXt(in_chans=1, num_classes=2).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=2.5e-4, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-6)

num_epochs = 2
train_losses, val_losses = [], []
train_accuracies, val_accuracies, val_f1s = [], [], []
best_val_acc = 0.0
'''
# Create the model ConvNeXt-Tiny (the ConvNeXt block stages and channels are set by default)
model = ConvNeXt(in_chans=1, num_classes=2).to(device)

# Define hyperparameters
label_smoothing = 0.1
class_weights = count_classes(train_ds)
learning_rate = 2.5e-4
weight_decay = 1e-4
num_epochs = 120
num_warmup_epochs = 10

# Create lists for storing losses, accuracies, and f1 scores for plotting
train_losses, val_losses = [], []
train_accuracies, val_accuracies, val_f1s = [], [], []
best_val_acc = 0.0 # This is the variable used to store the best validation accuracy during training
patience = 20 # This is how many epochs the training loop should wait for the validation accuracy to improve before stopping early
epochs_without_improvement = 0 # The number of epochs since the validation accuracy improved
early_stop = False

# Define the loss criterion
criterion = nn.CrossEntropyLoss(label_smoothing=label_smoothing, weight=torch.tensor(class_weights, dtype=torch.float32, device=device))

# Define the optimiser to be used
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

# Define the learning rate scheduler
scheduler1 = LinearLR(optimizer, start_factor=0.1, total_iters=num_warmup_epochs) # Uses linear learning rate for the first few epochs to warmup
scheduler2 = CosineAnnealingLR(optimizer, T_max=(num_epochs - num_warmup_epochs), eta_min=1e-6) # Switches to cosine annealing learning rate after warmup
scheduler = SequentialLR(optimizer, schedulers=[scheduler1, scheduler2], milestones=[num_warmup_epochs]) # Combines the individual schedulers

save_dir = cwd

print("Starting training\n")

for epoch in range(1, num_epochs + 1):
    print(f"\nEpoch {epoch}/{num_epochs}")
    print("-" * 40)

    # Calculate the accuracies, losses, and f1 scores for the training and validation sets across 1 epoch; update the parameters of the model according to the training set results
    train_loss, train_acc, _ = run_epoch(model, train_loader, criterion=criterion, optimizer=optimizer, train=True)
    val_loss, val_acc, val_f1 = run_epoch(model, val_loader, criterion=criterion, optimizer=None, train=False)

    # Add the calculates accuries, losses, and f1 scores to a list
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    val_f1s.append(val_f1)

    scheduler.step() # Step the learning rate scheduler each epoch

    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
    print(f"Val   Loss: {val_loss:.4f} | Val Acc:   {val_acc:.2f}% | F1: {val_f1:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        os.makedirs(save_dir, exist_ok=True)
        torch.save(model.state_dict(), os.path.join(save_dir, "best_convnext_adni.pth")) #os.path.join(cwd, "best_convnext_adni.pth")
        print(f"✅ New best model saved (Val Acc = {best_val_acc:.2f}%)")
        epochs_without_improvement = 0  # reset the number of epochs without improvement when an improvement happens
    else:
      epochs_without_improvement += 1
      print(f"No improvement for {epochs_without_improvement} epoch(s).")

      if epochs_without_improvement >= patience: # Stop early if the number of epochs without improvement exceeds the patience
          print(f"Early stopping triggered after {epoch} epochs.")
          early_stop = True
          break

print("\nTraining complete.")
print(f"Best Validation Accuracy: {best_val_acc:.2f}%")

def plot_learning_curves(train_losses, val_losses, train_accuracies, val_accuracies, val_f1s):
    """
    Plot the learning curves for the model, including a plot of the accuracy and
    loss for the training set vs. the validation set as well as a plot of the
    validation set's f1 scores.

    Arguments:
      train_losses: a list of the training losses for each epoch
      val_losses: a list of the validation losses for each epoch
      train_accuracies: a list of the training accuracies for each epoch
      val_accuracies: a list of the validation accuracies for each epoch
      val_f1s: a list of the validation f1 scores for each epoch
    """
    epochs = range(1, len(train_losses) + 1)
    plt.figure(figsize=(18, 5))

    # Training vs. validation loss each epoch
    plt.subplot(1, 3, 1)
    plt.plot(epochs, train_losses, "r-", label="Train Loss")
    plt.plot(epochs, val_losses, "g-", label="Validation Loss")
    plt.title("Training vs Validation Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.legend()

    # Training vs. validation accuracy each epoch
    plt.subplot(1, 3, 2)
    plt.plot(epochs, train_accuracies, "r-", label="Train Accuracy")
    plt.plot(epochs, val_accuracies, "g-", label="Validation Accuracy")
    plt.title("Training vs Validation Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy (%)")
    plt.grid(True)
    plt.legend()

    # Validation f1 score each epoch
    plt.subplot(1, 3, 3)
    plt.plot(epochs, val_f1s, "-b", label="Validation F1 Score")
    plt.title("Validation F1 Score")
    plt.xlabel("Epoch")
    plt.ylabel("F1 Score")
    plt.grid(True)
    plt.legend()

    plt.tight_layout()
    plt.show()

plot_learning_curves(train_losses, val_losses, train_accuracies, val_accuracies, val_f1s)

model.load_state_dict(torch.load(os.path.join(save_dir, "best_convnext_adni.pth"), map_location=device)) # Evaluate the model using the parameters saved for the highest validation accuracy

accuracy, all_preds, all_targets, all_probs = evaluate_model(model, test_loader, device) # Evaluate the model

plot_confusion_matrix(all_targets, all_preds) #Plot confusion matrices